# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages: miniUI

before_install:
  - git clone https://github.com/zint/zint.git ../zint
  - cd ../zint
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - sudo cp /usr/local/lib/libzint.* /usr/lib
  - cd ..
  - cd ../CannaFrontdesk

# won't be able to suppress some warnings
warnings_are_errors: false

env:
  global:
  - secure: NkXQAMzTWFm9Oruy1aKkbZli2bR05JmGKXXW/Y0y50KQW9YM/k1RKZidsf9qeYwIvC/IFQWYQ6j3yQs+c6YckbW8G26agezH/28KdqTwFfLakoR5uHtnnDKBSOgng3fwMtJccg5Zdv4JLmV6+bTxCZeyH6DSz4Xso0CQpYWWmJDZSsa0gL1iXAWven4oH9lHs/6OukOBpLcyo2Lr+seqU7mh/5EE+BFTIOWnPV9gtxvTQjjw1DkoHivL68cl84SpUR3C169GUYZFV0O86MtxM3NJyu+9CXsLemXXjpzDsXw4TlnO5mmHG0rkpttP/FvHGh6jlK5ML9Ytqnu7fgQ41Uew2nDHkUDPyRIETlzvWoWnEW8wME1YaWZ3ZYxd7ZhxAD7bG0nBwMSGzFUQUx3CTOLc/wzJ4zmI5+e/PACVx6KIQJgRtyLCBa0hHcE/HaPQdSiGFAjh/yRYip4TTHOBrsBzgh/hrmJ65W8KZgWG8nPnlFsSpw5PQcOduMRCSHuzrLn+doa9Lei2ZsK/Zab0yTaAVtQj9GoRG0gmS+H3xponn0JMkbGxEuYSJPulGJjUx7T9uWETt7detw/dP1sVVSgWl5p3JjOtzaNmFeuW55KyLDnJy253tLSNVyyupuPY+AF8mZkqgA82XOyMSQhJo/YjYY6bDOCeVtRGWVB4UIQ=
  
after_success:
      - test $TRAVIS_PULL_REQUEST == "false" && 
        test $TRAVIS_BRANCH == "master" && 
        bash deploy.sh