# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages: miniUI

before_install:
  - git clone https://github.com/zint/zint.git ../zint
  - cd ../zint
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - sudo cp /usr/local/lib/libzint.* /usr/lib
  - cd ..
  - cd ../CannaFrontdesk

# won't be able to suppress some warnings
warnings_are_errors: false